// <auto-generated />
namespace JBUniversity.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CommentedoutFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentedoutFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202012041550437_Commented out FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
